### ISSUE TITLE
Distorted Scrolling on Addition of Item and Upwards Scroll

### ISSUE THREAD

**Issue by thedillonb** [smileyborg/TableViewCellWithAutoLayoutiOS8#16]
I've seen this on a few projects and am starting to believe this is an iOS bug. However, if you scroll to the bottom, add a new item, and start scrolling upwards you'll notice that the scroll jumps all over the place.

Steps to reproduce:

1) Scroll to the bottom
2) Hit the "+" for a new item
3) Gently scroll to the top

**Comment by smileyborg** [comment]
This is likely the same issue with Apple's (buggy) row height estimation that has come up many times, see here for more discussion: #8 If this is the same issue, please do file a radar with Apple so this gets fixed!

Let me know if you don't think this is the same issue and I can investigate more.
