### ISSUE TITLE
Jumpy scrolling when rotating device

### ISSUE THREAD

**Issue by christianselig** [smileyborg/TableViewCellWithAutoLayoutiOS8#18]
Has anyone found a solution to the issue (present in the sample project) where if you scroll a bit, rotate the device, then scroll back up the cells are very jumpy and the scrolling seems off?

**Comment by smileyborg** [comment]
This is a duplicate of #17. I don't know of any workarounds at this moment, if you or anyone else figures it out please do share!

**Comment by deville** [comment]
Have the same problem after navigating to another view controller and back:
`navigationController?.pushViewController(UIViewController(), animated: true)`

The iOS7 approach still works https://github.com/smileyborg/TableViewCellWithAutoLayout
