### ISSUE TITLE
TableView jumps

### ISSUE THREAD

**Issue by ranjitk-plackal** [smileyborg/TableViewCellWithAutoLayoutiOS8#20]
Hello,

When I use this 

 [m_tableView beginUpdates];
    [m_tableView deleteRowsAtIndexPaths:[NSArray arrayWithObject:m_indexPath] withRowAnimation:UITableViewRowAnimationFade];
    [m_tableView endUpdates];

and

 [m_tableView beginUpdates];
    [m_tableView reloadRowsAtIndexPaths:[NSArray arrayWithObject:m_indexPath] withRowAnimation:UITableViewRowAnimationFade];
    [m_tableView endUpdates];

tableView jumps, it happens because of this

  m_tableView.estimatedRowHeight = 97.0;
    m_tableView.rowHeight = UITableViewAutomaticDimension;

But then if we remove this, then we will not variable height.

So guys please help me out..

Here is my SO question for same

http://stackoverflow.com/questions/29079485/reloadrowsatindexpath-weird-behaviour-for-uitableview

Regards
Ranjit

**Comment by smileyborg** [comment]
Hi Ranjit,

This is almost certainly the same issue as #17. Please take a look at that thread for further information.

**Comment by ranjitk-plackal** [comment]
Hello smileyborg,
So there is no solution for this?

**Comment by smileyborg** [comment]
As discussed in #17, this is an Apple bug, with no known workaround.
