### ISSUE TITLE
Setting a cell's UITableViewCellAccessoryType creates an overly tall app

### ISSUE THREAD

**Issue by stevemoser** [smileyborg/TableViewCellWithAutoLayoutiOS8#25]
Setting
`cell.accessoryType = UITableViewCellAccessoryType.DisclosureIndicator`
in `cellForRowAtIndexPath` causes cells to be created with lots of padding between the two labels.

**Comment by smileyborg** [comment]
Are you using the iOS 8 self-sizing cell mechanism? Because if you're doing it the iOS 7 way, this is a known limitation, see here for more details: https://github.com/smileyborg/TableViewCellWithAutoLayout/issues/11

**Comment by stevemoser** [comment]
Sorry I should have specified. I am using self sizing cells.

I actually found a fix. I just set the accessory type in the tableView's `willDisplayCell` method and that fixes my layout issues. It seems like Apple is leaning towards doing more cell configuration in `willDisplayCell` than in `cellForRowAtIndexPath`. Or at least their sample code suggests that.

**Comment by smileyborg** [comment]
Good to know! You may want to also test on iOS 9 because they have fixed a number of outstanding bugs in the betas so far. This sounds more like a bug to me, it should work either way IMO.
