### ISSUE TITLE
swift: compiler error

### ISSUE THREAD

**Issue by filipmelik** [smileyborg/TableViewCellWithAutoLayoutiOS8#27]
Hello, I've just cloned the project and tried to compile swift version without any modifications, but I've run into following issue:

Xcode Version 6.4 (6E35b), iOS SDK 8.4
<img width="1396" alt="screen shot 2015-08-16 at 18 18 26" src="https://cloud.githubusercontent.com/assets/5735485/9294113/7a56ee0e-4443-11e5-9f1c-fa6aec9fa60d.png">

Do you compile project without any problems? Thanks 
Filip

**Comment by smileyborg** [comment]
Hi Filip,

Commit daaef5e3185d6c43b865a20144d540804cd5492b made some changes for compatibility with Xcode 7 & Swift 2.0. You can revert that commit if you want to build the app using Xcode 6.4.

**Comment by filipmelik** [comment]
thanks for the quick response Tyler.

**Comment by smileyborg** [comment]
No worries! I also realized the README still said Xcode 6 was required, so I just fixed that :)
