### ISSUE TITLE
Code does not compile

### ISSUE THREAD

**Issue by achikin** [smileyborg/TableViewCellWithAutoLayoutiOS8#28]
There is an error in code:
TableViewCell.swift:
```
required init?(coder aDecoder: NSCoder)
{
     super.init(coder: aDecoder)   
     setupViews()
}
```
TableViewCell.swift:30:14: Failable initializer 'init(coder:)' cannot override a non-failable initializer

**Comment by smileyborg** [comment]
Hi Anton, this is a duplicate of #27.
