### ISSUE TITLE
Some setup requirements?

### ISSUE THREAD

**Issue by retzion** [smileyborg/TableViewCellWithAutoLayoutiOS8#29]
I downloaded, opened, and ran, but I get an error. Little help? Thanks.
<img width="1440" alt="screenshot 2015-10-03 10 33 38" src="https://cloud.githubusercontent.com/assets/1813451/10263890/c0e6f1e2-69ba-11e5-947d-c3bce21ef412.png">

**Comment by smileyborg** [comment]
This should have been fixed by 448a38ad3ed053f155aefe54094d536c1f5826fa, please try opening the `.xcworkspace` file.
