### ISSUE TITLE
Title label does not grow to size

### ISSUE THREAD

**Issue by damionjn** [smileyborg/TableViewCellWithAutoLayoutiOS8#34]
I've been having a hard time figuring out the self-sizing cells for the past two days. I think I've re-read your answer [here on SO](http://stackoverflow.com/questions/18746929/using-auto-layout-in-uitableview-for-dynamic-cell-layouts-variable-row-heights/18746930#18746930) 20 times; I want to say I understand how this works, but I can't get this to work for the life of me.

I finally got fed up, wiped out all of my work, copy-pasted the UITableViewCell & UITableViewController subclasses from this project into mine and get the following:
![screen shot 2015-12-23 at 10 24 44 pm](https://cloud.githubusercontent.com/assets/7221494/11989977/25020bb4-a9c4-11e5-9eb1-5b983c9b5cfc.png)

Here's my cell and controller (basically copy-paste besides the label text):
![screen shot 2015-12-23 at 10 24 24 pm](https://cloud.githubusercontent.com/assets/7221494/11989995/661e04f4-a9c4-11e5-9793-ec5b9c50ebab.png)

And my storyboard attributes so you know no funny-business is going on there:
![screen shot 2015-12-23 at 10 31 14 pm](https://cloud.githubusercontent.com/assets/7221494/11990033/0679e2ce-a9c5-11e5-8924-27ceac65aff0.png)
![screen shot 2015-12-23 at 10 31 20 pm](https://cloud.githubusercontent.com/assets/7221494/11990034/0691f904-a9c5-11e5-981c-9cd040413bc4.png)

**Comment by damionjn** [comment]
I had also toyed with:
- The code inside `layoutIfNeeded()` in the tableViewCell class
- Updating the cell frame & contentView bounds in the `cellForRowAtIndexPath` in the tableViewController (commented out)
- Setting the `preferredMaxLayoutWidth` for both labels

After looking at the other issues, no luck so far.

**Comment by AndroidLTG** [comment]
me too

**Comment by damionjn** [comment]
@AndroidLTG Take a look at this, it's the simplest I could make it without wiping out all of my work. Just pay attention to `titleLabel` & `descriptionLabel` and you should be in Dynamic Cell Height Heaven: https://gist.github.com/damionjn/85e2b17cdcde07ca4533
