### ISSUE TITLE
Self sizing issue with 3 UILabels inside a cell

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [smileyborg/TableViewCellWithAutoLayoutiOS8#7]
Hi,

I'm kinda stomped by this issue. Its going to be a little lengthy but please bear with me.

This issue came across in an iOS 8 app I'm creating. I've set all the constraints so I'm not getting any auto layout errors or warnings. But when I run it, it looks like this.

![rsz_ios_simulator_screen_shot_sep_21_2014_112239_pm](https://cloud.githubusercontent.com/assets/2551877/4349574/8d015796-41bb-11e4-933e-8a599418bc99.png)

The blue and the black labels are supposed to resize themselves to fit their content thus making the cell's height dynamic. I've set the number of lines of both of those labels to 0 as well.

Here's a weird thing that happens. If I rotate the device to landscape and back to portrait, I get this.

![rsz_ios_simulator_screen_shot_sep_21_2014_112247_pm](https://cloud.githubusercontent.com/assets/2551877/4349580/d24d81f8-41bb-11e4-9a77-e344d701abf6.png)

Now the black label has resized itself to fit all its text but it overflows the cells boundaries. I have set these two lines of code in the `viewDidLoad()` method.

```
tableView.estimatedRowHeight = 100
tableView.rowHeight = UITableViewAutomaticDimension
```

I've uploaded a test Xcode project to [Dropbox](https://www.dropbox.com/s/mym2gl3w8l73dch/Layout.zip?dl=0) demonstrating this issue so it'll be easier for you to give it a look. Can you please help me out to resolve this?

Thank you.
# 

EDIT: After I ran into this issue, I came across this [tutorial](http://www.raywenderlich.com/73602/dynamic-table-view-cell-height-auto-layout). Although it's on iOS 7, I picked up a few pointers regarding auto layout. So I created a separate project to test them out.

Basically what I did was moved the 3 labels closer to each other so that their vertical spaces would be 0 (I did this because that's how it was done in this tutorial's example project but I noticed in your project, you could have different vertical space values). And added other constraints to the sides. No auto layout errors or warnings again.

When I run it the first time, the black label cropping issue is still there.

![rsz_ios_simulator_screen_shot_sep_21_2014_115649_pm](https://cloud.githubusercontent.com/assets/2551877/4349631/9f1b7ef0-41bd-11e4-8ebb-426d877b824f.png)

But I turn it to landscape and back again to portrait and..

![rsz_ios_simulator_screen_shot_sep_21_2014_115700_pm](https://cloud.githubusercontent.com/assets/2551877/4349632/ac39ee8c-41bd-11e4-901e-0e0696b7ccbc.png)

all the all the cells are resized properly to fit both labels! Still can't figure out why this doesn't happen in the first run though. I uploaded a separate project to [here](https://www.dropbox.com/s/fn7gsj05z3t1a62/SelfSizingCellsIssue.zip?dl=0) (This project has 2 cells. One with 3 labels and one with 2 labels. I was just experimenting. The same issue came up in both of these scenarios).
# 

My actual issue is the first one. I just added the second part to show a different approach I took. 

If you could take a look. I'd really appreciate it. This issue has me stomped.

Thank you.

**Comment by koenvanderdrift** [comment]
Could anyone confim that with a `UILabel` sublass in the code from @kevinrenskers above, `layoutSubviews` seems to be no longer needed for my `UITableViewCell` subclass?

**Comment by bandish09** [comment]
hello @smileyborg  @Isuru-Nanayakkara  and @kevinrenskers .... guys i have same problem...and i am trying from last one week...but still facing same error every time...can you please send me demo project?

**Comment by koenvanderdrift** [comment]
Is the `preferredMaxLayoutWidth` fix still needed on iOS 9 and onwards?
